"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminCommand = void 0;
var AdminCommand;
(function (AdminCommand) {
    AdminCommand["Statistics"] = "moonshot:statistics";
    AdminCommand["Leaderboards"] = "moonshot:leaderboards";
    AdminCommand["TopBets"] = "moonshot:leaderboards:bets";
    AdminCommand["Users"] = "moonshot:users";
    AdminCommand["User"] = "moonshot:user";
    AdminCommand["CreateUser"] = "moonshot:users:create";
    AdminCommand["UpdateUser"] = "moonshot:users:update";
    AdminCommand["CreatePromocodes"] = "moonshot:promocodes:create";
    AdminCommand["Tag"] = "moonshot:promocodes:tag";
    AdminCommand["Tags"] = "moonshot:promocodes:tags";
    AdminCommand["CreateTag"] = "moonshot:promocodes:tags:create";
    AdminCommand["Referrals"] = "moonshot:referrals";
    AdminCommand["Giveaway"] = "moonshot:giveaway";
    AdminCommand["Giveaways"] = "moonshot:giveaways";
    AdminCommand["CreateGiveaway"] = "moonshot:giveaways:create";
    AdminCommand["UpdateGiveaway"] = "moonshot:giveaways:update";
    AdminCommand["DeleteGiveaway"] = "moonshot:giveaways:delete";
    AdminCommand["Rules"] = "moonshot:rules";
    AdminCommand["UpdateRules"] = "moonshot:rules:update";
})(AdminCommand = exports.AdminCommand || (exports.AdminCommand = {}));
